# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vlcrb}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nashby"]
  s.date = %q{2011-05-01}
  s.description = %q{Ruby wrapper for libVLC}
  s.email = %q{younash@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "examples/1.flv",
    "examples/libvlc_tutorial.rb",
    "lib/vlcrb.rb",
    "lib/vlcrb/ffi/libvlc.rb",
    "lib/vlcrb/ffi/libvlc_events.rb",
    "lib/vlcrb/ffi/libvlc_media.rb",
    "lib/vlcrb/ffi/libvlc_media_discoverer.rb",
    "lib/vlcrb/ffi/libvlc_media_library.rb",
    "lib/vlcrb/ffi/libvlc_media_list.rb",
    "lib/vlcrb/ffi/libvlc_media_list_player.rb",
    "lib/vlcrb/ffi/libvlc_media_player.rb",
    "lib/vlcrb/ffi/libvlc_structures.rb",
    "lib/vlcrb/ffi/libvlc_vlm.rb",
    "lib/vlcrb/ffi/types.rb",
    "lib/vlcrb/ffi/vlc.rb",
    "lib/vlcrb/version.rb",
    "test/helper.rb",
    "test/test_vlcrb.rb",
    "vlcrb.gemspec"
  ]
  s.homepage = %q{http://github.com/nashby/vlcrb}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby wrapper for libVLC}
  s.test_files = [
    "examples/libvlc_tutorial.rb",
    "test/helper.rb",
    "test/test_vlcrb.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<ffi-swig-generator>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<ffi-swig-generator>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<ffi-swig-generator>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<ffi-swig-generator>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<ffi-swig-generator>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<ffi-swig-generator>, [">= 0"])
  end
end

