require 'ffi'

require 'vlcrb/ffi/libvlc'
require 'vlcrb/ffi/libvlc_media'
require 'vlcrb/ffi/libvlc_events'
require 'vlcrb/ffi/libvlc_media_discoverer'
require 'vlcrb/ffi/libvlc_media_library'
require 'vlcrb/ffi/libvlc_media_list'
require 'vlcrb/ffi/libvlc_media_list_player'
require 'vlcrb/ffi/libvlc_media_player'
require 'vlcrb/ffi/libvlc_structures'
require 'vlcrb/ffi/libvlc_vlm'
require 'vlcrb/ffi/libvlc_media_discoverer'
require 'vlcrb/ffi/vlc'
